services:
  postgres:
    image: postgres
    container_name: game-reviews-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - game-review-data:/var/lib/postgresql/data
    networks:
      - game-review-network
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: game-reviews-backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - game-review-network
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: game-reviews-fronend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=${BACKEND_HOST}${BACKEND_PORT}
    networks:
      - game-review-network

volumes:
  game-review-data:

networks:
  game-review-network:
    driver: bridge